package binatang;

/**
 *
 * @author sye
 */
public class SuaraBinatang extends javax.swing.JFrame {

    /**
     * Creates new form SuaraBinatang
     */
    public SuaraBinatang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnimalGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radKucing = new javax.swing.JRadioButton();
        radAnjing1 = new javax.swing.JRadioButton();
        radAnjing2 = new javax.swing.JRadioButton();
        radAyam1 = new javax.swing.JRadioButton();
        radAyam2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtSuara = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaKet = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suara Binatang");
        setPreferredSize(new java.awt.Dimension(606, 372));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Silahkan pilih suara binatang berikut:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AnimalGroup.add(radKucing);
        radKucing.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        radKucing.setText("Kucing");
        radKucing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radKucingActionPerformed(evt);
            }
        });

        AnimalGroup.add(radAnjing1);
        radAnjing1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        radAnjing1.setText("Anjing 1");
        radAnjing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAnjing1ActionPerformed(evt);
            }
        });

        AnimalGroup.add(radAnjing2);
        radAnjing2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        radAnjing2.setText("Anjing 2");
        radAnjing2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAnjing2ActionPerformed(evt);
            }
        });

        AnimalGroup.add(radAyam1);
        radAyam1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        radAyam1.setText("Ayam 1");
        radAyam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAyam1ActionPerformed(evt);
            }
        });

        AnimalGroup.add(radAyam2);
        radAyam2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        radAyam2.setText("Ayam 2");
        radAyam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAyam2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAyam2)
                    .addComponent(radAyam1)
                    .addComponent(radAnjing2)
                    .addComponent(radAnjing1)
                    .addComponent(radKucing))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radKucing)
                .addGap(18, 18, 18)
                .addComponent(radAnjing1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(radAnjing2)
                .addGap(18, 18, 18)
                .addComponent(radAyam1)
                .addGap(18, 18, 18)
                .addComponent(radAyam2)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("Suara");

        txtSuara.setEditable(false);
        txtSuara.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setText("Keterangan");

        txaKet.setEditable(false);
        txaKet.setColumns(20);
        txaKet.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        txaKet.setRows(5);
        jScrollPane1.setViewportView(txaKet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(328, 328, 328))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(170, 170, 170))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuara, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSuara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(372, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radKucingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radKucingActionPerformed
        Kucing kucing = new Kucing();
        kucing.nama = "Kucing";
        txtSuara.setText(kucing.suara());
        txaKet.setText(kucing.toString());
        
    }//GEN-LAST:event_radKucingActionPerformed

    private void radAnjing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAnjing1ActionPerformed
        Anjing anjing = new Anjing();
        anjing.nama = "Anjing 1";
        txtSuara.setText(anjing.suara());
        txaKet.setText(anjing.toString());
    }//GEN-LAST:event_radAnjing1ActionPerformed

    private void radAnjing2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAnjing2ActionPerformed
        Anjing anjing = new Anjing();
        anjing.nama = "Anjing 2";
        txtSuara.setText(anjing.suara(anjing));
        txaKet.setText(anjing.toString());
    }//GEN-LAST:event_radAnjing2ActionPerformed

    private void radAyam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAyam1ActionPerformed
        Ayam ayam = new Ayam();
        ayam.nama = "Ayam 1";
        txtSuara.setText(ayam.suara());
        txaKet.setText(ayam.toString());
    }//GEN-LAST:event_radAyam1ActionPerformed

    private void radAyam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAyam2ActionPerformed
        Ayam ayam = new Ayam();
        ayam.nama = "Ayam 2";
        txtSuara.setText(ayam.suara(ayam));
        txaKet.setText(ayam.toString());
    }//GEN-LAST:event_radAyam2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaraBinatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaraBinatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaraBinatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaraBinatang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaraBinatang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AnimalGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radAnjing1;
    private javax.swing.JRadioButton radAnjing2;
    private javax.swing.JRadioButton radAyam1;
    private javax.swing.JRadioButton radAyam2;
    private javax.swing.JRadioButton radKucing;
    private javax.swing.JTextArea txaKet;
    private javax.swing.JTextField txtSuara;
    // End of variables declaration//GEN-END:variables
}
